import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/toggle-theme";
import HomeRedirect from "@/components/ui/home_redirect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real State App AI",
  description: "Generated by GRK, this is a search engine for real state properties. It uses AI to search for properties with natural language.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-0 right-10 p-4 flex gap-2 z-50">
            <HomeRedirect />
            <ModeToggle />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
