import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/toggle-theme";
import Logo from "@/components/ui/logo";
import { Analytics } from "@vercel/analytics/react"
import {
  SignInButton,
  UserButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import ClerkProviderWrapper from "@/components/ClerkProviderWrapper";
import { Button } from "@/components/ui/button";
import LocaleSwitcher from "@/components/locale-switcher";
import { i18n, type Locale } from '@/i18n-config';
import { LocaleProvider } from "@/contexts/localeContext";
import Footer from "@/components/ui/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real State AIpp",
  description: "Generated by GRK, this is a search engine for real state properties. It uses AI to search for properties with natural language.",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}


export default function RootLayout({
  children,
  params,

}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };

}>) {
  const locale = params.lang;
  const afterSignOutUrl = `/${locale}`;

  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProviderWrapper lang={params.lang}>
            <LocaleProvider initialLocale={params.lang}>
              <div className="fixed z-50 pl-40 pt-5 hidden lg:block">
                <Logo lang={params.lang} />
              </div>

              <div className="fixed flex top-0 right-0 p-4 z-50 items-center">
                <SignedOut>
                  <Button variant="outline">
                    <SignInButton />
                  </Button>
                </SignedOut>

                <div className="mr-4">
                  <SignedIn>
                    <UserButton afterSignOutUrl={afterSignOutUrl} />
                  </SignedIn>
                </div>

                <div className="hidden lg:block">
                  <LocaleSwitcher />
                  <ModeToggle />
                </div>

              </div>
              <div className="flex flex-col fex-l1 overflow-y-auto min-h-screen pt-28">
                <main className="flex-grow">
                  {children}
                </main>
                <Footer />
              </div>
              <Analytics />
            </LocaleProvider>

          </ClerkProviderWrapper>
        </ThemeProvider>

      </body>
    </html>
  );
}